// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsbalwsijrlriaxrqreu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYmFsd3NpanJscmlheHJxcmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTQzMjQsImV4cCI6MjA2MjQ5MDMyNH0.kv3wVlaZSNMokHYMlUpAN4m4I5i6blBp5UDcOR6ZxzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);